
// D Raphahlelo 223076058
// SM Swana 223430145
// MG MANAKA 223607436
// T Mokhuamathe 223569550
// BB MSIMANGA 223821411 


package vut.gui;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import vut.Book;
import vut.EBook;
import vut.PrintBook;


public class BookEntry extends javax.swing.JFrame {

    public static ArrayList<Book> bookList = new ArrayList<>();
   
    /**
     * Creates new form BookEntry
     */
    public BookEntry() {
        initComponents();
        fillCmboWeight();
        fillCmboPages();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        txtAuthor = new javax.swing.JTextField();
        txtIsbnNo = new javax.swing.JTextField();
        txtFileSize = new javax.swing.JTextField();
        btnSaveBook = new javax.swing.JButton();
        cmboPages = new javax.swing.JComboBox<>();
        cmboWeight = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDisplay = new javax.swing.JTextArea();
        btnViewWeightOfBooks = new javax.swing.JButton();
        btnViewSizeOfBooks = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Book Entry Screen");

        jLabel1.setText("Book title :");

        jLabel2.setText("Author :");

        jLabel3.setText("ISBN no :");

        jLabel4.setText("File size :");

        btnSaveBook.setText("Save Book");
        btnSaveBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveBookActionPerformed(evt);
            }
        });

        taDisplay.setColumns(20);
        taDisplay.setRows(5);
        jScrollPane1.setViewportView(taDisplay);

        btnViewWeightOfBooks.setText("View Weight of Books");
        btnViewWeightOfBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewWeightOfBooksActionPerformed(evt);
            }
        });

        btnViewSizeOfBooks.setText("View Size of Books");
        btnViewSizeOfBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSizeOfBooksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTitle)
                            .addComponent(txtAuthor)
                            .addComponent(txtIsbnNo)
                            .addComponent(txtFileSize, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnSaveBook, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(251, 251, 251)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmboPages, 0, 329, Short.MAX_VALUE)
                                .addComponent(cmboWeight, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnViewWeightOfBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(56, 56, 56)
                            .addComponent(btnViewSizeOfBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIsbnNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFileSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSaveBook, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmboPages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmboWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewSizeOfBooks, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(btnViewWeightOfBooks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveBookActionPerformed
        // TODO add your handling code here:
        try{
            String title = txtTitle.getText();
            String author = txtAuthor.getText();
            String isbnNo = txtIsbnNo.getText();
            
            if(isbnNo.startsWith("0")){
                int fileSize = Integer.parseInt(txtFileSize.getText());
                bookList.add(new EBook( author,title, isbnNo,fileSize));
            }else if(isbnNo.startsWith("1")){
                String cmbOPages = (String) cmboPages.getSelectedItem();
                int noOfPages = Integer.parseInt(cmbOPages);
                
                String weight = (String) cmboWeight.getSelectedItem();
                float weightOfBook = Float.parseFloat(weight);
                
                bookList.add(new PrintBook(author, title, isbnNo, noOfPages, weightOfBook));
            }
            
             taDisplay.setText(bookList.get(bookList.size() - 1 ).toString());
             
             
        }catch (IllegalArgumentException e) {
               JOptionPane.showMessageDialog(this, e.getMessage(), "Error Message", JOptionPane.ERROR_MESSAGE);
          }
    }//GEN-LAST:event_btnSaveBookActionPerformed

    private void btnViewWeightOfBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewWeightOfBooksActionPerformed
        // TODO add your handling code here:
        
        taDisplay.setText(null);

          String display = "Weight of PrintBooks  \n";
          
          for(Book obj: bookList)  {          
               //snce weight is associated with printbook
               if (obj instanceof PrintBook) {
                    //display using the getsizedetails method
                    display += obj.getSizeDetails() + "\n";
               }
          }
               
          taDisplay.setText(display);
    }//GEN-LAST:event_btnViewWeightOfBooksActionPerformed

    private void btnViewSizeOfBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSizeOfBooksActionPerformed
        // TODO add your handling code here:
        
        taDisplay.setText(null);

          String display = "Book size information  \n";
          
          for(Book obj: bookList)  {          

                    display += obj.getSizeDetails() + "\n";        
          }
               
          taDisplay.setText(display);
    }//GEN-LAST:event_btnViewSizeOfBooksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookEntry().setVisible(true);
            }
        });
    }
    
   
    private void fillCmboPages() {
        
        cmboPages.removeAllItems();
        cmboPages.addItem("Select pages here");
        for (int i = 400; i <= 2000; i += 50) {
            cmboPages.addItem(String.valueOf(i));
        }
    }

   
    private void fillCmboWeight() {
        
        cmboWeight.removeAllItems();
        cmboWeight.addItem("Select book weight here");
        for (int i = 1000; i <= 2000; i += 5) {
            cmboWeight.addItem(String.valueOf(i));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveBook;
    private javax.swing.JButton btnViewSizeOfBooks;
    private javax.swing.JButton btnViewWeightOfBooks;
    private javax.swing.JComboBox<String> cmboPages;
    private javax.swing.JComboBox<String> cmboWeight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taDisplay;
    private javax.swing.JTextField txtAuthor;
    private javax.swing.JTextField txtFileSize;
    private javax.swing.JTextField txtIsbnNo;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
